#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Bitwarden state=floating

picom --backend glx &
sh $HOME/.config/polybar/hack/scripts/pywal.sh $HOME/.config/wallpapers/
sh $HOME/.config/polybar/hack/launch.sh &
setxkbmap ch &
xinput set-prop 12 319 1 &
xsetroot -cursor_name left_ptr &
sxhkd &
sh $HOME/.config/dunst/launchdunst.sh &
